In [33]:
import numpy as np

In [34]:
class TicTacToe:
    def __init__(self, size=3):
        self.board = np.zeros((size, size))
        self.current_turn = 1


In [35]:
class MonteCarloSearch:
    def __init__(self):
        pass

    def traverse():
        pass

    def rollout():
        pass

    def rollout_policy():
        pass

    def backpropagate():
        pass

    def best_child():
        pass

In [37]:

game = TicTacToe(size=3)

game.board[0,0] = -1
game.board[1,1] = 1 

print(game.board)
    

[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
